version: "3.8"

services:
  #Servizio del database dell'intera applicazione
  database:
    platform: linux/x86_64
    image: mongo:4.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    restart: "no"
    networks:
      - my-network

  loginService:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: LOGIN_Service
    ports:
      - "8080:8080"
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - database
    networks:
      - my-network
    volumes:
      - ./AuthorizationMS/LoginMS/build/libs/SmartCityWasteManagement-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar


  smartbinsManagementService:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: SMARTBINS_SERVICE
    ports:
      - "8081:8080"
      - "8001:8000"
    expose:
      - "8001"
    depends_on:
      - database
    networks:
      - my-network
    volumes:
      - ./SmartBinMS/build/libs/SmartBinMS-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001 -jar /app/app.jar


  citizenManagementService:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: CITIZEN_SERVICE
    ports:
      - "8082:8080"
      - "8002:8000"
    expose:
      - "8002"
    depends_on:
      - database
    networks:
      - my-network
    volumes:
      - ./CitizenMS/build/libs/CitizenMS-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8002 -jar /app/app.jar



networks:
  my-network:
    driver:
      "bridge"
    
volumes:
  mongodb_data:

