version: "3.8"

services:
  #Servizio del database dell'intera applicazione
  database:
    platform: linux/x86_64
    image: mongo:4.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    restart: "no"
    networks:
      - my-network


  rabbitmq:
    build:
      context: ./
    hostname: "rabbit"
    ports:
      - "5672:5672"  # Porta per le connessioni AMQP
      - "15672:15672"  # Porta per l'interfaccia di gestione web
      - "1883:1883"   # Porta per MQTT
      - "61613:61613" # Porta per STOMP
    networks:
      - my-network


  loginService:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: LOGIN_Service
    ports:
      - "8080:8080"
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - database
    networks:
      - my-network
    volumes:
      - ./AuthorizationMS/LoginMS/build/libs/SmartCityWasteManagement-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar


  smartbinsManagementService:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: SMARTBINS_SERVICE
    ports:
      - "8081:8080"
      - "8001:8000"
    expose:
      - "8001"
    depends_on:
      - database
    networks:
      - my-network
    volumes:
      - ./SmartBinMS/build/libs/SmartBinMS-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001 -jar /app/app.jar


  citizenManagementService:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: CITIZEN_SERVICE
    ports:
      - "8082:8080"
      - "8002:8000"
    expose:
      - "8002"
    depends_on:
      - database
    networks:
      - my-network
    volumes:
      - ./CitizenMS/build/libs/CitizenMS-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8002 -jar /app/app.jar

  disposalManagementService:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: DISPOSAL_SERVICE
    ports:
      - "8083:8080"
      - "8003:8000"
    expose:
      - "8003"
    depends_on:
      - database
      - rabbitmq
    networks:
      - my-network
    volumes:
      - ./DisposalMs/build/libs/DisposalMS-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8003 -jar /app/app.jar

  alarmsMS:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: ALARMS_SERVICE
    ports:
      - "8084:8080"
      - "8004:8000"
    expose:
      - "8004"
    depends_on:
      - database
      - rabbitmq
    networks:
      - my-network
    volumes:
      - ./AlarmsMS/build/libs/AlarmsMS-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8004 -jar /app/app.jar


  taxService:
    platform: linux/x86_64
    image: openjdk:17-jdk-alpine
    container_name: TAX_SERVICE
    ports:
      - "8085:8080"
      - "8005:8000"
    expose:
      - "8005"
    depends_on:
      - database
    networks:
      - my-network
    volumes:
      - ./TaxMS/build/libs/TaxMS-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8005 -jar /app/app.jar

networks:
  my-network:
    driver:
      "bridge"
    
volumes:
  mongodb_data:

