name: Update Submodules

on:
  workflow_dispatch: 

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive' 

      - name: Set up Git credentials
        run: |
          git config --global user.email "accoglicarmine.a@gmail.com"  
          git config --global user.name "carmineaccogli"  

      - name: Update submodules
        run: |
          cd .
          git submodule update --init --recursive --remote
