name: Update Submodules

on:
  workflow_dispatch: 

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git credentials
        run: |
          git config --global user.email "accoglicarmine.a@gmail.com"  
          git config --global user.name "carmineaccogli"  # Cambia con il tuo nome utente Git

      - name: Update submodules
        run: |
          cd .
          git submodule update --init --recursive --remote
