name: Update Submodules

on:
  push:
    branches:
      - main  

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permissions for update_submodules.sh
        run: chmod +x ./.github/update_submodules.sh

      - name: Run update_submodules.sh script
        run: ./.github/update_submodules.sh  
